name: Deploy BMW Fixed API

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apis/bmw/src/bmw_auth_fix.py'
      - 'apis/bmw/src/main_fixed.py'

env:
  FUNCTION_NAME: bmw_api_fixed
  REGION: europe-west6
  GCP_PROJECT: miavia-422212

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_PRODUCTION }}
    
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Prepare deployment
      run: |
        cd apis/bmw
        # Copy the fixed implementation to main.py for deployment
        cp src/main_fixed.py main.py
        # Ensure requirements.txt is in the right place
        cp requirements.txt .
    
    - name: Deploy Fixed BMW API
      working-directory: apis/bmw
      run: |
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --gen2 \
          --runtime python310 \
          --region ${{ env.REGION }} \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point bmw_api_fixed \
          --source .
    
    - name: Get Function URL
      run: |
        FUNCTION_URL=$(gcloud functions describe ${{ env.FUNCTION_NAME }} \
          --region ${{ env.REGION }} \
          --project ${{ env.GCP_PROJECT }} \
          --format 'value(serviceConfig.uri)')
        echo "Function deployed to: $FUNCTION_URL"
        echo "Test with: curl -X POST $FUNCTION_URL -H 'Content-Type: application/json' -d '{...}'"